[package]
name = "vpcsubnetcalc"
version = "0.0.1"
edition = "2024"

[dependencies]
ipnetwork = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
